cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/build

language: php

php:
  - 7.1
  - 7.2
  - 7.3

script:
  - if [[ $TRAVIS_PHP_VERSION == "7.1" ]]; then make test-coveralls; else make test; fi

after_success:
  - if [[ $TRAVIS_PHP_VERSION == "7.1" ]]; then composer require php-coveralls/php-coveralls --prefer-source; fi
  - if [[ $TRAVIS_PHP_VERSION == "7.1" ]]; then php vendor/bin/php-coveralls -v; fi
